### ISSUE TITLE
Cannot read property 'lcid' of undefined

### ISSUE THREAD

**Issue by thechriskent** [MakingThingsWorkToronto/jQuery.spHtmlEditor#1]
In following your initial instructions of just placing the spHtmlEditor call on my div within the document ready function, I was getting the error: *Cannot read property 'lcid' of undefined*

I fixed this by using ExecuteOrDelayUntilScriptLoaded like this:

    $(document).ready(function(){
        ExecuteOrDelayUntilScriptLoaded(function(){
            $('#myRTEbox').spHtmlEditor({version:"onprem"});
        },'sp.js');
    });

**I think this plugin is awesome!** I just wanted to leave this here for anyone else looking for an answer. Really, this isn't an issue with your plugin, but more of an addendum to your ReadMe. Thanks for making this!

**Comment by MakingThingsWorkToronto** [comment]
Thanks for the comment - will update the readme!  Ya those cursed JavaScript resource files need to load before this works - a bit frustrating.

**Comment by MakingThingsWorkToronto** [comment]
Updated the documentation!
