### ISSUE TITLE
Uncaught TypeError: $(...).spHtmlEditor is not a function. Update : Its Resolved.

### ISSUE THREAD

**Issue by akashsabhahit** [MakingThingsWorkToronto/jQuery.spHtmlEditor#2]
Hello,
I am trying to follow the instructions to render the rich text field on an HTML page, which is being linked to a Content Editor Webpart on a SP page on Office365. 
I am getting 2 errors,

1) In the spHtmlEditor.js itself saying "Uncaught SyntaxError: Unexpected token <". 
![image](https://cloud.githubusercontent.com/assets/15966477/11323890/4849c706-9146-11e5-938a-7fcaf00fe75a.png)
 This is for the first line of the JS.
2) On calling the Html Editor on document.ready, I am getting the following error "Uncaught TypeError: $(...).spHtmlEditor is not a function".

Here is code which I have written on the HTML Page, all references are working as expected.

![image](https://cloud.githubusercontent.com/assets/15966477/11323913/bd6f69fa-9146-11e5-8a1d-e0a1485b0693.png)

Please let me know if I am making any mistakes to invoke this. 
Thanks !

**Comment by MakingThingsWorkToronto** [comment]
Is it possible the plugin JavaScript code was modified when it was downloaded?  I'd suggest grabbing again & updating.  I cannot see any syntax errors that would cause the plugin to fail like this.

**Comment by akashsabhahit** [comment]
Hello,

Just noting an observation which might be helpful for others, as it certainly resolved my issue.

For the problem above, downloaded using the "Download Zip" option to get a correct file.Thanks for the suggestion

However, we still facing the issue where "https://cdn.sharepointonline.com/16290/_layouts/15/16.0.4208.1226/" was not accessible. 

To resolve this issue, just removed what looked like an IP i.e 16.0.4208.1226, and it worked ! This is the link which worked for me: 
"https://cdn.sharepointonline.com/16290/_layouts/15/"

And lastly many thanks for creating this server side control as setting these complex fields on Office365 is really tedious and components like these help to get stuff implemented in a more manageable way. 

Thanks !
