### ISSUE TITLE
Ribbon does not load correctly if you first call method 'add' and then 'sethtml'

### ISSUE THREAD

**Issue by benlime** [MakingThingsWorkToronto/jQuery.spHtmlEditor#3]
Actually I initialize the `spHtmlEditor()` control with the defaults in an onprem environment. After that, i request the html content from the server and call `spHtmleditor({method: 'sethtml', data: html})`.

When I do that and try to click inside the RTE, the ribbon is broken. You will have to do at least a double-click in the "Format Text" Ribbon Tab.

I assume it's an issue with the `fixRibbonLoader()` method which initializes the ribbon twice. I added the following code at the end of the `fixRibbonLoader()` and now it's working. 

```javascript
SP.SOD.executeOrDelayUntilScriptLoaded(function() {      
    if (!SP.Ribbon.PageManager.get_instance().get_ribbon())
        _ribbonStartInit("Ribbon.Read", false, null);
}, 'sp.ribbon.js');
```

Anyway, thank you for this awesome plugin!

**Comment by MakingThingsWorkToronto** [comment]
Thanks for the awesome feedback - I will have to circle back and test this again!  Appreciate the heads up!

**Comment by MakingThingsWorkToronto** [comment]
This should be resolved with the current version.  Please reopen if not working.  Thanks!
