### ISSUE TITLE
Unable to get property 'registerPasteMode' of undefined or null reference

### ISSUE THREAD

**Issue by jkuter** [MakingThingsWorkToronto/jQuery.spHtmlEditor#4]
In SharePoint 2016 I get "Unable to get property 'registerPasteMode' of undefined or null reference" after initializing a new instance.  If I change to the Office 365 version of the RTE I get the same error.  It all works fine for the same code/site in SharePoint 2013.  I noticed the error after testing our upgrade to 2016 from 2013.

**Comment by onizet** [comment]
Hello, I encountered the same error and fixed it by modifying load_onprem() with

```
function load_onprem(ready, path) {
        var p = path || "/_layouts/15/";

        var spVersion = parseInt(_spPageContextInfo.siteClientTag.match(/\$\$(\d{2})\./i)[1], 10);
        if (spVersion >= 16 && (typeof (g_all_modules) == "undefined"
			|| typeof (g_all_modules["ms.rte.js"]) == "undefined")
			&& $("#msrtejs").length == 0)
            $('<script id="msrtejs" type="text/javascript" src="' + p + 'ms.rte.js">' + '</' + 'script>').appendTo("body");

        if ((typeof (g_all_modules) == "undefined"
			|| typeof (g_all_modules["sp.ui.rte.js"]) == "undefined")
			&& $("#spuirtejs").length == 0)
            $('<script id="spuirtejs" type="text/javascript" src="' + p + 'sp.ui.rte.js">' + '</' + 'script>').appendTo("body");

        ExecuteOrDelayUntilScriptLoaded(function () {
            ready();
        }, "sp.ui.rte.js");

}
```

**Comment by jkuter** [comment]
I see, there is an extra/new id in there.  Thanks I will give it a shot.

**Comment by jkuter** [comment]
Awesome!  It works great.  Thanks for the quick fix.

**Comment by MakingThingsWorkToronto** [comment]
Thanks for the feedback guys - got me back to fix some basic issues with the plugin.

One more note: "sp.ui.rte.js" does have a dependency on "ms.rte.js".  You will need to ensure ms.rte.js is fully loaded before loading sp.ui.rte.js to avoid that error.  Likely a ctrl+f5 on above code fix would result in the same error.

This should be resolved with the commit today.

**Comment by jkuter** [comment]
Thanks!  I really appreciate the effort on the plugin.  I use it for a custom internal tool at my company and it works great for our purpose.

**Comment by onizet** [comment]
Nice catch effectively. Thanks also for your plugin, it's very useful :-)
