### ISSUE TITLE
Ribbon Embed Code option disabled

### ISSUE THREAD

**Issue by lsuarezj** [MakingThingsWorkToronto/jQuery.spHtmlEditor#5]
actually It is more a question than an error.
There's a way to enable the ribbon options on the insert tab?

I need to enable the embed Code option.

thanks

**Comment by thastarkmtw** [comment]
Not an outlandish request however not supported right now.

I did run a test, if you add the following at line 63 the ribbon button will be enabled (before the RTE.Canvas.fixRegion(eid, false); call):

edit[0].AllowEmbedding  = 'True';

There does seem to be a SP imposed security restriction thereafter which I don't have time to investigate right now.  Let me know if you make progress.

**Comment by lsuarezj** [comment]
Thanks for the quick answer and for the approach, it works for me right now. I'll keep working on this and let you know if find something.

**Comment by arulkarthik** [comment]
Everything Working fine except select an asset (picture,video)from sharepoint in insert tab.
